server {
    #Nginx escuchará en el puerto 80.
    listen 80;

    # Cuando alguien entre a: http://localhost Nginx intentará abrir: index.php
    index index.php index.html;

    #El proyecto comienza en:
    root /var/www/public;

    # Cuando llegue una petición, intenta encontrar el archivo. Si no existe, envíasela a Laravel
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Significa: "Si el archivo termina en .php..." Entonces: fastcgi_pass php:9000; Le dice: "...envíaselo al contenedor llamado php, puerto 9000."
    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;

        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}